const data = [
  {
    id: "1",
    position: "Member",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: "ID007",
  },

  {
    id: "1",
    position: "Member",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "arrived",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "arrived",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "Moderator",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "canceled",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "Member",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "arrived",
    actions: " ",
  },
  {
    id: "1",
    position: "Member",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "arrived",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
  {
    id: "1",
    position: "User",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "arrived",
    actions: " ",
  },
  {
    id: 4,
    position: "Moderator",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "coming",
    actions: " ",
  },
];

export default data;
