import demopf from "assets/img/pp1.jpg";
const data = [
  {
    profilePhoto: demopf,
    occupation: "Entreprenuer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: "ID007",
  },

  {
    profilePhoto: demopf,
    occupation: "Entreprenuer",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "accepted",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "accepted",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Graphic Designer",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "rejected",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Entreprenuer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "accepted",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Entreprenuer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "accepted",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    occupation: "Software Engineer",
    name: "arshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "accepted",
    actions: " ",
  },
  {
    profilePhoto: demopf,
    id: 4,
    occupation: "Graphic Designer",
    name: "Harshil Patel",
    date: "11/2/2000",
    location: "Ahmedabad",
    status: "pending",
    actions: " ",
  },
];

export default data;
